FROM williamyeh/ansible:ubuntu16.04

WORKDIR /tmp
COPY  .  /tmp/ansible-openssh-server

RUN echo 127.0.0.1 > inventory

RUN ansible-playbook -i inventory ansible-openssh-server/tests/provision.yml --connection=local --sudo
